name: aura_external_wallet
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.1
  uuid: ^4.0.0-beta3-1

  aura_launcher:
    path: plugins/aura_launcher

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
